[tool.poetry]
name = "cfn_lint_serverless"
version = "0.3.3"
description = "Serverless rules for cfn-lint"
authors = ["Amazon Web Services"]
readme = "README.md"
license = "MIT-0"

[tool.poetry.dependencies]
python = ">=3.8.1,<4"
cfn-lint = "^1.12.4"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-cov = "^5.0.0"
coverage = "^7.6.1"
black = "^24.0"
flake8 = "^7.1.1"
flake8-variables-names = "^0.0.6"
flake8-eradicate = "^1.5.0"
flake8-bugbear = "^24.8.19"
bandit = "^1.7.0"
radon = "^5.1.0"
xenon = "^0.9.0"
isort = "^5.13.2"

[tool.black]
line-length = 120
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | example
)
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
