version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    labels:
      - chore
  
  - package-ecosystem: pip
    directory: /cfn-lint-serverless
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    labels:
      - chore

  - package-ecosystem: gomod
    directory: /tflint-ruleset-aws-serverless
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    labels:
      - chore