area/cfn-lint:
  - cfn-lint-serverless/**

area/tflint:
  - tflint-ruleset-aws-serverless/**

documentation:
  - any:
      - docs/**
      - examples/**
    all: 
      - "!cfn-lint-serverless/**"
      - "!tflint-ruleset-aws-serverless/**"