site_name: Serverless Rules
site_description: Serverless Rules for checking infrastructure-as-code templates against serverless recommended practices.
site_author: Amazon Web Services
repo_url: https://github.com/awslabs/serverless-rules
repo_name: awslabs/serverless-rules
edit_uri: edit/develop/docs

nav:
  - Homepage: index.md
  - Usage:
    - "With cfn-lint": cfn-lint.md
    - "With tflint": tflint.md
  - Rules:
    - Home: rules/index.md
    - "API Gateway": rules/api_gateway.md
    - AppSync: rules/appsync.md
    - EventBridge: rules/eventbridge.md
    - Lambda: rules/lambda.md
    - SQS: rules/sqs.md
    - "Step Functions": rules/step_functions.md
  - Contributing:
    - "Creating rules": contributing/create_rule.md

theme:
  name: material
  palette:
    scheme: default
    primary: teal
    accent: deep orange
  logo: images/aws-logo-light.svg
  favicon: images/aws-logo-light.svg
  features:
    - navigation.sections

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed

copyright: Copyright &copy; 2021 Amazon Web Services