name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Set release notes tag
        run: |
          export RELEASE_TAG_VERSION=${{ github.event.release.tag_name }}
          echo "RELEASE_TAG_VERSION=${RELEASE_TAG_VERSION:1}" >> $GITHUB_ENV
      - name: Ensure version in cfn-lint-serverless
        run: |
          grep "version = \"${RELEASE_TAG_VERSION}\"" cfn-lint-serverless/pyproject.toml
      - name: Ensure version in tflint-ruleset-aws-serverless
        run: |
          grep "Version: \"${RELEASE_TAG_VERSION}\"" tflint-ruleset-aws-serverless/main.go
      - name: Install dependencies
        run: |
          make dev
      - name: Run all checks
        run: |
          make pr
      - name: Upload to PyPi
        run: |
          make -C cfn-lint-serverless release
        env:
          PYPI_USERNAME: __token__
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  update_docs:
    needs: publish
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}